apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: exemple
  name: exemple
spec:
  selector:
    matchLabels:
      app: exemple
  template:
    metadata:
      annotations:
      labels:
        app: exemple
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
      nodeSelector:
        seulement: sur_certains_noeuds
