apiVersion: apps/v1
kind: Deployment
metadata:
    name: ipetnoeud
    labels:
        app: ipetnoeud
spec:
    replicas: 6
    selector:
        matchLabels:
            app: ipetnoeud
    template:
        metadata:
            labels:
                app: ipetnoeud
        spec:
            containers:
                - name: ipetnoeud
                  image: diablotin/ip-et-noeud
                  env:
                      - name: ID_NOEUD
                      valueFrom:
                          fieldRef:
                              fieldPath: spec.nodeName
