apiVersion: v1
kind: Pod
metadata:
    name: pod2-donnees-persistantes
spec:
    containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: fichierswebstatiques
      mountPath: /usr/share/nginx/html
    volumes:
    - name: fichierswebstatiques
      hostPath:
          path: /donnees_pour_le_web
