apiVersion: v1
kind: Pod
metadata:
        name: pod-avec-garde-fou
spec:
        containers:
        - name: nginx
          image: nginx:alpine
          resources:
                  limits:
                     memory: 90Mi
