apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    etape: test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
  nodeSelector:
    transcodeur: TOTO
