apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumenfs
  labels:
    volume: unvolumenfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 10.0.0.100
    path: "/partage"
