apiVersion: v1
kind: Pod
metadata:
  name: webdp
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "100Mi"
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: fichierswebstatiques
  volumes:
    - name: fichierswebstatiques
      hostPath:
        path: /donnees_pour_le_web
