apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demande-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: unvolumenfs
