apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minage
  name: minage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: minage
  template:
    metadata:
      labels:
        app: minage
    spec:
#      nodeSelector:                 # il ne peut y avoir qu'une seule clef carte-graphique
#        carte-graphique: NV3625B
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: carte-graphique
                    operator: In
                    values:
                      - NV3625B
                      - ASUS4712X
      containers:
        - image: nginx:alpine
          name: mineur
