apiVersion: v1
kind: Pod
metadata:
  name: pod-custom
spec:
  containers:
    - name: serveurweb
      image: nginx:alpine
      resources:
        limits:
          memory: 20Mi
      env:
        - name: BAVARD
          valueFrom:
            configMapKeyRef:
              name: essaiconfig
              key: bavard
