apiVersion: v1
kind: Pod
metadata:
  name: pod-avec-donnees-persistantes
  namespace: prod
spec:
  containers:
    - name: serveurweb
      image: nginx:alpine
      resources:
        limits:
          memory: 20Mi
      volumeMounts:
        - name: fichierswebstatiques
          mountPath: /usr/share/nginx/html
  volumes:
    - name: fichierswebstatiques
      hostPath:
        path: /donnees_pour_le_web
